export const genderIdentities: string[] = [
  "Agender",
  "Abimegender",
  "Adamas gender",
  "Aerogender",
  "Aesthetigender",
  "Affectugender",
  "Agenderflux",
  "Alexigender",
  "Aliusgender",
  "Amaregender",
  "Ambigender",
  "Ambonec",
  "Amicagender",
  "Androgyne",
  "Anesigender",
  "Angenital",
  "Anogender",
  "Anongender",
  "Antegender",
  "Anxiegender",
  "Apagender",
  "Apconsugender",
  "Astergender",
  "Astral gender",
  "Autigender",
  "Autogender",
  "Axigender",
  "Bigender",
  "Biogender",
  "Blurgender",
  "Boyflux",
  "Burstgender",
  "Caelgender",
  "Cassgender",
  "Cassflux",
  "Cavusgender",
  "Cendgender",
  "Ceterogender",
  "Ceterofluid",
  "Cisgender",
  "Cloudgender",
  "Collgender",
  "Colorgender",
  "Commogender",
  "Condigender",
  "Deliciagender",
  "Demifluid",
  "Demiflux",
  "Demigender",
  "Domgender",
  "Duragender",
  "Egogender",
  "Epicene",
  "Esspigender",
  "Exgender",
  "Existigender",
  "Femfluid",
  "Femgender",
  "Fluidflux",
  "Gemigender",
  "Genderblank",
  "Genderflow",
  "Genderfluid",
  "Genderfuzz",
  "Genderflux",
  "Genderpuck",
  "Genderqueer",
  "Gender witched",
  "Girlflux",
  "Healgender",
  "Mirrorgender",
  "Omnigender",
  "Male",
  "Female",
  "Non-binary",
  "Genderqueer",
  "Genderfluid",
  "Attack Helicopter",
  "Apache Helicopter",
  "Potato",
  "Unicorn",
  "Toaster",
  "Dragonkin",
  "Shark",
  "Alien",
  "Robot",
  "Furry",
  "Dolphin",
  "Your mom",
  "McLaren",
  "Lambo",
  "Audi",
  "Kawasaki Ninja",
  "Walmart Bag",
  "Biology Textbook",
  "Body bag",
  "Computer",
  "Sleeping Bag",
  "Note book",
  "Text book",
  "Image book",
  "Gender",
  "Compiler",
  "Interpreter",
  "I'd rather not say",
  "Your mom's unwashed cloth",
  "Lmao",
  "Dirty",
  "Pervert",
  "Ambivert",
  "Introvert",
  "Extrovert",
  "Hex",
  "RGB",
  "HSL",
  "HLS",
  "Sun",
  "Moon",
  "Heart Attack",
  "Rest",
  "Your mom's pin",
  "Inital",
  "Pin",
  "Blueberry",
  "Strawberry",
  "Jackfruit",
  "Mango",
  "Lichi",
];
