export const roleMap = {
  "🥣": "Abimegender",
  "🐸": "Adamas gender",
  "😵": "Aerogender",
  "🧧": "Aesthetigender",
  "😘": "Affectugender",
  "😱": "Agender",
  "💙": "Agenderflux",
  "👀": "Anogender",
  "🎶": "Alien",
  "💀": "Aliusgender",
  "🔑": "Ambigender",
  "😁": "I'd rather not say",
  "💣": "Ambonec",
  "👉": "Amaregender",
  "🎱": "Amicagender",
  "💋": "Androgyne",
  "💎": "Anesigender",
  "👂": "Angenital",
  "👨‍⚖️": "Anongender",
  "⛵": "Antegender",
  "📉": "Anxiegender",
  "🙌": "Apache Helicopter",
  "💰": "Apagender",
  "🐶": "Male",
  "👽": "Astral gender",
  "🐎": "Astergender",
  "🏆": "Attack Helicopter",
  "🍀": "Audi",
  "💄": "Autigender",
  "👨‍🔬": "Autogender",
  "🎄": "Axigender",
  "🎏": "Bigender",
  "😈": "Biogender",
  "👋": "Biology Textbook",
  "🐬": "Blurgender",
  "❤": "Blueberry",
  "🐰": "Body bag",
  "🔥": "Boyflux",
  "👨‍🦱": "Burstgender",
  "🚲": "Caelgender",
  "🐩": "Cassflux",
  "🌹": "Cassgender",
  "🦅": "Cavusgender",
  "😉": "Cendgender",
  "🚗": "Ceterofluid",
  "☹️": "Ceterogender",
  "💝": "Cisgender",
  "🐍": "Cloudgender",
  "💶": "Collgender",
  "🐳": "Colorgender",
  "🏅": "Compiler",
  "😓": "Computer",
  "🌙": "Condigender",
  "🚽": "Deliciagender",
  "🌺": "Demifluid",
  "🎀": "Demiflux",
  "⚾": "Demigender",
  "🔬": "Dirty",
  "✌": "Dolphin",
  "🍸": "Domgender",
  "🏁": "Dragonkin",
  "👊": "Duragender",
  "🌟": "Egogender",
  "💖": "Epicene",
  "🐟": "Esspigender",
  "💘": "Exgender",
  "👃": "Existigender",
  "🦏": "Extrovert",
  "👄": "Femfluid",
  "🕶️": "Femgender",
  "🗿": "Fluidflux",
  "☀": "Furry",
  "🦎": "Gemigender",
  "🏀": "Gender",
  "🍻": "Genderblank",
  "👶": "Genderflow",
  "🐻": "Genderfluid",
  "⚽": "Genderflux",
  "🎁": "Genderfuzz",
  "💛": "Genderpuck",
  "😡": "Genderqueer",
  "💩": "Gender witched",
  "👸": "Girlflux",
  "😂": "Heart Attack",
  "🌈": "Healgender",
  "😜": "Hex",
  "🐷": "HLS",
  "😝": "HSL",
  "🐫": "Image book",
  "🪇": "Inital",
  "🐵": "Interpreter",
  "🎎": "Introvert",
  "👿": "Jackfruit",
  "💃": "Kawasaki Ninja",
  "💜": "Lambo",
  "💽": "Lichi",
  "💪": "Lmao",
  "🥢": "Mango",
  "💚": "McLaren",
  "🐮": "Mirrorgender",
  "🏈": "Moon",
  "🎾": "Non-binary",
  "🎋": "Note book",
  "😍": "Omnigender",
  "🍉": "Pervert",
  "🎐": "Pin",
  "🌊": "Potato",
  "🍳": "RGB",
  "👠": "Rest",
  "🍓": "Robot",
  "😳": "Shark",
  "🙏": "Sleeping Bag",
  "⛄": "Strawberry",
  "👌": "Sun",
  "🚀": "Text book",
  "🔫": "Toaster",
  "🍎": "Unicorn",
  "🎍": "Walmart Bag",
  "🎈": "Your mom",
  "🎉": "Your mom's pin",
  "🐙": "Your mom's unwashed cloth",
};
